### PR TITLE
Fixing the multiple author issue

### LINKED ISSUE #2: Unable to add emails and affiliations to authors in title of paper.
Hi @Hoverbear , love this repo. I need some help in adding email addresses and university affiliations in the markdown title. I added them up like this 
```markdown
---
title: Distributed and Parallel Databases Project Report
author:
 - name: Purushotham Kaushik Swaminathan
   email: purukaushik@asu.edu
 tags: [Distributed Databases]
abstract: 
```
and it didn't work

### PR DESCRIPTION
**Pull request by purukaushik**
@Hoverbear -- have attempted to fix the following issues I had raised:
1. Displaying multiple authors
2. Displaying affiliations of authors
3. Displaying email-ids of authors.
Fixes #2

### CODE REVIEW

**Comment by purukaushik** [comment]
Been having issues building on travis. Seems to be related to this [current issue with ghp-import](https://github.com/davisp/ghp-import/issues/57)

**Comment by Hoverbear** [comment]
It's still broken. :(

**Comment by purukaushik** [comment]
Looks like that issue with ghp-import is fixed with their 0.5.4 release. It worked on my machine now.

**Comment by purukaushik** [comment]
Works now. Tested it by building my repo -> https://purukaushik.github.io/acm-pandoc-paper/paper.pdf

**Comment by purukaushik** [comment]
I suspect your GH token might have expired/ been deleted. I am able to build [my fork ](https://travis-ci.org/purukaushik/acm-pandoc-paper/builds/185239487)

**Comment by Hoverbear** [comment]
Bah! You're probably right.

**Comment by Hoverbear** [comment]
@purukaushik Would you actually like to take over this repo? I don't really see myself using it in the future so I probably am a bad maintainer for it.

**Comment by purukaushik** [comment]
Yeah I can take over.

**Comment by Hoverbear** [comment]
I'll transfer it to you. :) Thanks!

**Comment by Hoverbear** [comment]
@purukaushik I merged the PR, to trasnfer the repo you need to purge your fork. :)

**Comment by purukaushik** [comment]
@Hoverbear purged my fork. ready for transfer 👍 .

**Comment by purukaushik** [comment]
@Hoverbear  - [this](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions) was probably why the build failed 🤔

**Comment by Hoverbear** [comment]
Ah yes makes sense.

**Pull request merged**
